sudo : required
services:
    - docker

before-install:
    - docker build -t vynaidu2020/docker-react -f Dockerfile_dev .

script:
    - docker run -e CI=true vynaidu2020/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-ap-south-1-425983501031"
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
        
    